seed: 806

model: SAMCorrCNNv1

density_pos_ce_lambda: 0.01
density_neg_ce_lambda: 0.01

# Backbone - SAM arch
clip_path: pretrained/ViT-B-16.pt
sam_path: pretrained/sam_vit_b.pth
txt_emb_dim: 512                  # CLIP Text
input_resolution: 512
img_emb_dim: 768
patch_size: 16

# Train
total_epochs: 500
batch_size: 4
num_workers: 8
valid_freq_epoch: 1
test_freq_epoch: 5

# Backbone - train
fix_txt_encoder: True
fix_img_encoder: True

# Data
use_cutmix: True
density_scale: 1
data_name: FSC147
data_root: datasets/FSC147_384_V2
img_norm_mean:
  - 0.485
  - 0.456
  - 0.406
img_norm_var:
  - 0.229
  - 0.224
  - 0.225

# Optimizer
weight_decay: 1.0e-4
backbone_lr: 1.0e-6
start_lr: 1.0e-4
end_lr: 1.0e-5
warm_up_iter: 300
last_lr_decay_iter: 40000

# Logging
img_summary_freq: 10
metric_summary_freq: 50
save_latest_freq: 500
save_every_freq_epoch: 25
