seed: 806

model: SAMMatMulCNN

# Data
density_scale: 60
data_name: FSC147
data_root: datasets/FSC147_384_V2
img_norm_mean:
  - 0.485
  - 0.456
  - 0.406
img_norm_var:
  - 0.229
  - 0.224
  - 0.225

# Optimizer
weight_decay: 1.0e-4
backbone_lr: 1.0e-6
start_lr: 1.0e-4
end_lr: 1.0e-5
warm_up_iter: 300
last_lr_decay_iter: 40000

# Logging
img_summary_freq: 100
metric_summary_freq: 50
save_latest_freq: 500
save_every_freq_epoch: 25
